// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShutTheTwelveServer.Data;

#nullable disable

namespace ShutTheBox.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20251007074148_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShutTheTwelveServer.Models.GameMove", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BoardStateAfter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BoardStateBefore")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dice1")
                        .HasColumnType("int");

                    b.Property<int>("Dice2")
                        .HasColumnType("int");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MoveNumber")
                        .HasColumnType("int");

                    b.Property<string>("NumbersUsed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("PlayerId");

                    b.ToTable("GameMoves");
                });

            modelBuilder.Entity("ShutTheTwelveServer.Models.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BotDifficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("int");

                    b.Property<int>("CurrentTurn")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GameMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAgainstBot")
                        .HasColumnType("bit");

                    b.Property<int>("LastDice1")
                        .HasColumnType("int");

                    b.Property<int>("LastDice2")
                        .HasColumnType("int");

                    b.Property<string>("Player1Board")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Player1Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Player1Score")
                        .HasColumnType("int");

                    b.Property<string>("Player2Board")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Player2Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Player2Score")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player2Id");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("ShutTheTwelveServer.Models.MatchHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ExpGained")
                        .HasColumnType("int");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("bit");

                    b.Property<Guid?>("OpponentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OpponentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ScoreGained")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("PlayerId");

                    b.ToTable("MatchHistories");
                });

            modelBuilder.Entity("ShutTheTwelveServer.Models.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BestStreak")
                        .HasColumnType("int");

                    b.Property<string>("ClientVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastMonthlyReset")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastWeeklyReset")
                        .HasColumnType("datetime2");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("MonthlyScore")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalDraws")
                        .HasColumnType("int");

                    b.Property<int>("TotalLosses")
                        .HasColumnType("int");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int");

                    b.Property<int>("TotalWins")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("WeeklyScore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("ShutTheTwelveServer.Models.PlayerCard", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PowerCardId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PlayerId", "PowerCardId");

                    b.HasIndex("PowerCardId");

                    b.ToTable("PlayerCards");
                });

            modelBuilder.Entity("ShutTheTwelveServer.Models.PowerCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PowerCost")
                        .HasColumnType("int");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UnlockLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PowerCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Lock one die and reroll the other",
                            IconUrl = "",
                            IsActive = true,
                            Name = "Lock & Reroll",
                            PowerCost = 15,
                            Rarity = 0,
                            Type = 0,
                            UnlockLevel = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Force opponent's die to roll 1-3",
                            IconUrl = "",
                            IsActive = true,
                            Name = "Sabotage",
                            PowerCost = 20,
                            Rarity = 0,
                            Type = 1,
                            UnlockLevel = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Reroll both dice if no moves",
                            IconUrl = "",
                            IsActive = true,
                            Name = "Second Chance",
                            PowerCost = 25,
                            Rarity = 1,
                            Type = 2,
                            UnlockLevel = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Set one die to 5 or 6",
                            IconUrl = "",
                            IsActive = true,
                            Name = "Wild Dice",
                            PowerCost = 30,
                            Rarity = 1,
                            Type = 3,
                            UnlockLevel = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "Steal opponent's dice roll",
                            IconUrl = "",
                            IsActive = true,
                            Name = "Steal Turn",
                            PowerCost = 35,
                            Rarity = 2,
                            Type = 4,
                            UnlockLevel = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "Block opponent's attack card",
                            IconUrl = "",
                            IsActive = true,
                            Name = "Shield",
                            PowerCost = 25,
                            Rarity = 2,
                            Type = 5,
                            UnlockLevel = 1
                        },
                        new
                        {
                            Id = 7,
                            Description = "Roll 3 times, keep best",
                            IconUrl = "",
                            IsActive = true,
                            Name = "Lightning Roll",
                            PowerCost = 40,
                            Rarity = 3,
                            Type = 6,
                            UnlockLevel = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = "Swap random numbers with opponent",
                            IconUrl = "",
                            IsActive = true,
                            Name = "Swap Board",
                            PowerCost = 30,
                            Rarity = 2,
                            Type = 7,
                            UnlockLevel = 1
                        },
                        new
                        {
                            Id = 9,
                            Description = "Copy opponent's last card",
                            IconUrl = "",
                            IsActive = true,
                            Name = "Mimic",
                            PowerCost = 35,
                            Rarity = 3,
                            Type = 8,
                            UnlockLevel = 1
                        });
                });

            modelBuilder.Entity("ShutTheTwelveServer.Models.PowerCardUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PowerCardId")
                        .HasColumnType("int");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("UsedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PowerCardId");

                    b.ToTable("PowerCardUsages");
                });

            modelBuilder.Entity("ShutTheTwelveServer.Models.GameMove", b =>
                {
                    b.HasOne("ShutTheTwelveServer.Models.GameSession", "GameSession")
                        .WithMany("GameMoves")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShutTheTwelveServer.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSession");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ShutTheTwelveServer.Models.GameSession", b =>
                {
                    b.HasOne("ShutTheTwelveServer.Models.Player", "Player1")
                        .WithMany("GameSessionsAsPlayer1")
                        .HasForeignKey("Player1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ShutTheTwelveServer.Models.Player", "Player2")
                        .WithMany("GameSessionsAsPlayer2")
                        .HasForeignKey("Player2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Player1");

                    b.Navigation("Player2");
                });

            modelBuilder.Entity("ShutTheTwelveServer.Models.MatchHistory", b =>
                {
                    b.HasOne("ShutTheTwelveServer.Models.GameSession", "GameSession")
                        .WithMany()
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShutTheTwelveServer.Models.Player", "Player")
                        .WithMany("MatchHistories")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSession");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ShutTheTwelveServer.Models.PlayerCard", b =>
                {
                    b.HasOne("ShutTheTwelveServer.Models.Player", "Player")
                        .WithMany("PlayerCards")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShutTheTwelveServer.Models.PowerCard", "PowerCard")
                        .WithMany("PlayerCards")
                        .HasForeignKey("PowerCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("PowerCard");
                });

            modelBuilder.Entity("ShutTheTwelveServer.Models.PowerCardUsage", b =>
                {
                    b.HasOne("ShutTheTwelveServer.Models.GameSession", "GameSession")
                        .WithMany("PowerCardUsages")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShutTheTwelveServer.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShutTheTwelveServer.Models.PowerCard", "PowerCard")
                        .WithMany()
                        .HasForeignKey("PowerCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSession");

                    b.Navigation("Player");

                    b.Navigation("PowerCard");
                });

            modelBuilder.Entity("ShutTheTwelveServer.Models.GameSession", b =>
                {
                    b.Navigation("GameMoves");

                    b.Navigation("PowerCardUsages");
                });

            modelBuilder.Entity("ShutTheTwelveServer.Models.Player", b =>
                {
                    b.Navigation("GameSessionsAsPlayer1");

                    b.Navigation("GameSessionsAsPlayer2");

                    b.Navigation("MatchHistories");

                    b.Navigation("PlayerCards");
                });

            modelBuilder.Entity("ShutTheTwelveServer.Models.PowerCard", b =>
                {
                    b.Navigation("PlayerCards");
                });
#pragma warning restore 612, 618
        }
    }
}
