// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShutTheTwelveBackend.Data;

#nullable disable

namespace ShutTheBox.Data.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShutTheBox.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameSessionId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("ShutTheTwelve.Backend.Models.DiceRoll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameSessionId")
                        .HasColumnType("int");

                    b.Property<string>("PlayerTurn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Roll1")
                        .HasColumnType("int");

                    b.Property<int>("Roll2")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.ToTable("DiceRolls");
                });

            modelBuilder.Entity("ShutTheTwelve.Backend.Models.GameSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActiveTurn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GameMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAIGame")
                        .HasColumnType("bit");

                    b.Property<string>("Player1Board")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Player1Cards")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Player1Id")
                        .HasColumnType("int");

                    b.Property<int>("Player1Score")
                        .HasColumnType("int");

                    b.Property<string>("Player2Board")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Player2Cards")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Player2Id")
                        .HasColumnType("int");

                    b.Property<int>("Player2Score")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalRounds")
                        .HasColumnType("int");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player2Id");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("ShutTheTwelve.Backend.Models.PowerCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EffectType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PowerCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 20,
                            Description = "Lock one die and reroll the other",
                            EffectType = "LockAndReroll",
                            IsActive = true,
                            Name = "Lock & Reroll"
                        },
                        new
                        {
                            Id = 2,
                            Cost = 25,
                            Description = "Opponent's next die rolls 1-3",
                            EffectType = "Sabotage",
                            IsActive = true,
                            Name = "Sabotage"
                        },
                        new
                        {
                            Id = 3,
                            Cost = 15,
                            Description = "Reroll if no moves available",
                            EffectType = "SecondChance",
                            IsActive = true,
                            Name = "Second Chance"
                        },
                        new
                        {
                            Id = 4,
                            Cost = 30,
                            Description = "Set one die to 5 or 6",
                            EffectType = "WildDice",
                            IsActive = true,
                            Name = "Wild Die"
                        },
                        new
                        {
                            Id = 5,
                            Cost = 35,
                            Description = "Steal opponent's roll result",
                            EffectType = "StealTurn",
                            IsActive = true,
                            Name = "Steal Turn"
                        },
                        new
                        {
                            Id = 6,
                            Cost = 15,
                            Description = "Block opponent's attack card",
                            EffectType = "Shield",
                            IsActive = true,
                            Name = "Shield"
                        },
                        new
                        {
                            Id = 7,
                            Cost = 40,
                            Description = "Roll 3 times, pick best",
                            EffectType = "LightningRoll",
                            IsActive = true,
                            Name = "Lightning Roll"
                        },
                        new
                        {
                            Id = 8,
                            Cost = 30,
                            Description = "Swap one number with opponent",
                            EffectType = "SwapBoard",
                            IsActive = true,
                            Name = "Swap Board"
                        },
                        new
                        {
                            Id = 9,
                            Cost = 25,
                            Description = "Copy opponent's last card",
                            EffectType = "Mimic",
                            IsActive = true,
                            Name = "Mimic"
                        });
                });

            modelBuilder.Entity("ShutTheTwelveBackend.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("ShutTheBox.Models.Message", b =>
                {
                    b.HasOne("ShutTheTwelve.Backend.Models.GameSession", "GameSession")
                        .WithMany("Messages")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSession");
                });

            modelBuilder.Entity("ShutTheTwelve.Backend.Models.DiceRoll", b =>
                {
                    b.HasOne("ShutTheTwelve.Backend.Models.GameSession", "GameSession")
                        .WithMany("DiceRolls")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSession");
                });

            modelBuilder.Entity("ShutTheTwelve.Backend.Models.GameSession", b =>
                {
                    b.HasOne("ShutTheTwelveBackend.Models.Player", "Player1")
                        .WithMany("GamesAsPlayer1")
                        .HasForeignKey("Player1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShutTheTwelveBackend.Models.Player", "Player2")
                        .WithMany("GamesAsPlayer2")
                        .HasForeignKey("Player2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Player1");

                    b.Navigation("Player2");
                });

            modelBuilder.Entity("ShutTheTwelve.Backend.Models.GameSession", b =>
                {
                    b.Navigation("DiceRolls");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("ShutTheTwelveBackend.Models.Player", b =>
                {
                    b.Navigation("GamesAsPlayer1");

                    b.Navigation("GamesAsPlayer2");
                });
#pragma warning restore 612, 618
        }
    }
}
